FROM node:20-slim

RUN apt-get update && \
    apt-get install -y curl bash unzip && \
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip -q awscliv2.zip && \
    ./aws/install && \
    rm -rf aws awscliv2.zip && \
    rm -rf /var/lib/apt/lists/*

RUN npm install -g aws-cdk@2.178.2 aws-cdk-local@2.19.2 esbuild ts-node typescript

WORKDIR /app
